### ISSUE TITLE
Disable popup notifications

### ISSUE THREAD

**Issue by MartinHaeusler** [orta/vscode-jest#104]
Hi,

I'm using VSCode on Windows with the Jest plugin. It is working nicely and doing exactly what is advertised. The problem is that every time I save a file, Jest runs (which is ok), but it also reports the successful of all executions with a **Windows notification message including sound**. 

**On. Every. Single. Save.**

Please consider the following options:
- Disable the popup altogether and find a less intrusive way to let users know that a test failed.
- Offer an option to turn the popup off.
- Remember the number of test failures in the last run, and only report something if this number changed compared to the previous execution.

Personally, I would like the third option best.

**Comment by orta** [comment]
I don't know if this is from the extension TBH, a vscode extension cannot play a sound. Can you show us what the notification looks like?

**Comment by MartinHaeusler** [comment]
Hi,
I am pretty sure that the sound is contributed by Windows 10 itself, it's the standard notification sound. The notification looks like this:

![image](https://cloud.githubusercontent.com/assets/16356998/26117726/bb1fb3a0-3a67-11e7-809b-6c91697bca95.png)

This notification pops right into my face every time I save a file. It's really distracting...

**Comment by bookman25** [comment]
That's a notification from jest.  You can set notify to false to turn that off: http://facebook.github.io/jest/docs/en/configuration.html#notify-boolean

**Comment by MartinHaeusler** [comment]
Oh, really? I thought it came from the VSCode plugin. I did not expect a command line program to publish such a notification. I'll try it, thanks!

**Comment by AndyOGo** [comment]
hmh, I have set `notify` to `false` within my `jest.config.js` file, but I still receive these notifications on mac OS X 🤔

**Comment by rveruna** [comment]
> hmh, I have set `notify` to `false` within my `jest.config.js` file, but I still receive these notifications on mac OS X 🤔

try to add "jest.enableSnapshotUpdateMessages": false to your vscode settings file.
