### ISSUE TITLE
test indicators not working(showing)

### ISSUE THREAD

**Issue by afaayerhan** [orta/vscode-jest#106]
the test indicators at the side and showing. even when the test has finished running I have a screenshot of what it is in the developer tools 
![image](https://cloud.githubusercontent.com/assets/8157594/26112597/072dd382-3a61-11e7-9792-de6b0bb005ce.png)
this question does not have to with my self promotion here. but i'm a fullstack Javascript/React/React-Native/Typescript developer. any looking to hire me ( especially something fulltime) can contact me on skype ayerhanafa

**Comment by afaayerhan** [comment]
more devtool screenshots 
![image](https://cloud.githubusercontent.com/assets/8157594/26144477/a433e852-3af1-11e7-81de-5fdfc597b791.png)

**Comment by afaayerhan** [comment]
your new jest release fixed it with no idea why. you are a magician @orta

**Comment by orta** [comment]
👍
