### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by crabicode** [orta/vscode-jest#11]
How can I run vscode-jest to include document as global?

It works with `npm run ./bin/test.js`

```js
//./bin/test.js
process.env.NODE_ENV = 'test';
process.env.PUBLIC_URL = '';

// Load environment variables from .env file. Suppress warnings using silent
// if this file is missing. dotenv will never modify any environment variables
// that have already been set.
// https://github.com/motdotla/dotenv
require('dotenv').config({
    silent: true
});

const jest = require('jest');
const argv = process.argv.slice(2);

// Watch unless on CI
if (!process.env.CI) {
    argv.push('--watch');
}

argv.push('--no-cache');

jest.run(argv);
```

**Comment by crabicode** [comment]
How can I supply `--env=jsdom` to the extension's options?

**Comment by orta** [comment]
Could that go inside your `Package.json` in the `jest` settings?

Otherwise, I think we can allow adding arbitrary commands as a workspace config?

**Comment by crabicode** [comment]
@orta 

having an option to override this args would suffice.

```js
//
var runtimeArgs = [
  '--json', '--useStderr', '--watch', 
  '--colors', 'false', "--jsonOutputFile", "/tmp/vscode-jest.json"
];
``` 

and consider adding an option to override your jest config with the one from `package.json` under `jest.*` as [jest doc](https://facebook.github.io/jest/docs/configuration.html#content) suggests

**Comment by crabicode** [comment]
@orta  [preset [string]](https://facebook.github.io/jest/docs/configuration.html#preset-string)

**Comment by orta** [comment]
this project runs: `jest --json --useStderr --watch --colors false --jsonOuputFile /tmp/vscode-jest.json` in the root project, in my projects it _does_ use the settings from my `Package.json`

Other than that, we do nothing unique to the project, can you run the above command normally? ^

**Comment by crabicode** [comment]
@orta yeap, you were right. it is working now, I just added the option after digging through jest docs.

```diff
# package.json
{
+  "testEnvironment": "jsdom"
}
```

Thank you!

**Comment by orta** [comment]
rock 👍

**Comment by orta** [comment]
Probably worth me adding some notes to the README for this - thanks @crabicode

**Comment by orta** [comment]
aha

so - this `ReferenceError: document is not defined ` happened to me, it should be fixed in 1.3.x now

**Comment by Altiano** [comment]
I use `create-react-app`, I have run `eject`.
I have configure `package.json`, but still got error

![image](https://cloud.githubusercontent.com/assets/8316282/26526660/79241238-43b4-11e7-82b6-aba0f053fec9.png)

**Comment by Altiano** [comment]
sorry, turns out it is already declared in package.json.
