### ISSUE TITLE
Wrong line numbers

### ISSUE THREAD

**Issue by fasa123** [orta/vscode-jest#118]
I get wrong line numbers by jest (and as thus this addon):

![bildschirmfoto-07 06 2017_04_56_32](https://user-images.githubusercontent.com/7671649/26860464-58dabab8-4b3e-11e7-8514-3c2b39d112e0.png)

Is this my fault, Jests fault, or this addons fault? Sourcemaps are obviously enabled (I just cloned this repo and opened it in vscode without editing anything besides intentionally failing a test). 

Also yes it is the same for a scratch Typescript/Jest project if my only test is a simple assertion like "expect(3).toEqual(4)".

I mean it looks pretty much like its jests fault still I don't get why it fails since sourcemaps (should be) availible.

**Comment by fasa123** [comment]
Appearently this was a mistake with the npm cache. After clearing it works again!

**Comment by orta** [comment]
Thanks for coming back with the answer 👍
