### ISSUE TITLE
Inline error messages are not showing

### ISSUE THREAD

**Issue by musicalshore** [orta/vscode-jest#120]
When my tests fail, `//` is appended to the line, but there is no message. Does this extension conflict with any others?

<img width="872" alt="vscode-jest" src="https://user-images.githubusercontent.com/1236455/27001356-c2a9ca1e-4d8d-11e7-8a6b-1a15c510fcbc.png">

**Comment by musicalshore** [comment]
Don't know why, but it started working on it's own after reloading vscode several times.

**Comment by tamj0rd2** [comment]
I'm having the same issue. Did you need to do anything else other than reloading/reopening vscode?

**Comment by stevenmusumeche** [comment]
Same issue here. It was working previously, but now I don't get the inline red/green dots even though I see in the toolbar at the bottom that it has run.
