### ISSUE TITLE
feature / mark skipped tests with a yellow (or whatever color) dot

### ISSUE THREAD

**Issue by buehler** [orta/vscode-jest#123]
Hey there!

Cool extension when one is working with jest!

One thing would be nice: if skipped tests would be marked with a yellow - or whatever color you like - dot. Just a nice to have thing ;-) Since right know, skipped tests are marked "green".

Cheers
Chris

**Comment by orta** [comment]
Nice thought, want to look into adding it? I think most of the work would need to happen in jest-editor-support

**Comment by buehler** [comment]
would be a good idea :-)

**Comment by buehler** [comment]
@orta got a question, (a little off-topic)
let's say I want to run jest tests via code instead of cli. would that be with the jest-editor-support package thingy as well?

So something like:
```typescript
import whatever to get jest.

jest.run('./test/**/*.ts');
```

or something like that.

**Comment by orta** [comment]
I'd love an API in jest-editor-support _for that_ but it isn't there today alas

**Comment by bookman25** [comment]
Skipped tests will be shown with the next release of `vscode-jest`
