### ISSUE TITLE
Code Highlights Missing

### ISSUE THREAD

**Issue by cgatian** [orta/vscode-jest#126]
### Environment

1. `node -v`: 8.0.0
2. `npm -v`: 5.0.4
4. `npm ls react-scripts` (if you haven’t ejected): ?

1. Operating system: Windows 10

### Steps to Reproduce
Install Jest plugin, run within project

### Expected Behavior
Decorators should be applied to code

### Actual Behavior
Plugin fails to show highlights for unit tests even though output runs correctly.

I've disabled all extensions in my work space (except Jest) and decorators are not showing.  Using VS Code 1.13.0.  There are no errors in the dev console.

![screen](https://user-images.githubusercontent.com/1752170/27875560-947a726c-6181-11e7-93e8-d0164def0099.PNG)

**Comment by cgatian** [comment]
This seems to work when `testRegex` is used and not `testMatch`

**Comment by orta** [comment]
Good catch, I didn't know testMatch exists - the [logic is here](https://github.com/orta/vscode-jest/blob/master/src/JestExt.ts#L292-L305), you're welcome to add support 👍

**Comment by cgatian** [comment]
@orta thanks for pointing me in the right direction. Ill give it a shot. No promises!
