### ISSUE TITLE
Can't interact with jest output

### ISSUE THREAD

**Issue by Haroenv** [orta/vscode-jest#127]
### Environment

1. `node -v`: [v8.1.3]
2. `npm -v`: [5.0.3]

1. Operating system: [macOS 10.12.5]

### Steps to Reproduce

1. Be in a test file
2. open the test runner
3. update a test that has snapshots multiple times
4. press `u` in the output panel

### Expected Behavior

The tests would update. The same for the other characters that are relevant (w, a, p, etc.)

### Actual Behavior

Nothing happens

**Comment by orta** [comment]
Afraid this is just the constraints of showing the Jest SDTOUT in VS Code's - I talked about what would need to happen for this to change here: https://github.com/orta/vscode-jest/issues/117#issuecomment-306485667
