### ISSUE TITLE
gutter icons are missing vscode 1.14.2

### ISSUE THREAD

**Issue by orenmizr** [orta/vscode-jest#130]
### Environment

1. `node -v`: 6.9.1
2. `npm -v`: 3+

1. Operating system: windows 10

### Steps to Reproduce
install extension
run - npm test or setup lanuch.json or "start jest runner"

### Expected Behavior

lines of code tested are marked with green icons at left side gutter if they pass. red if they fail

### Actual Behavior

no icons at the gutter. only status below in the bottom of the window. that says pass/fail

--- 

all setting seem to be true

**Comment by orenmizr** [comment]
i am using typescript with jest pre-processor - is that supported @orta ?

**Comment by orta** [comment]
TS + Jest is my setup everywhere 👍.

 I'd recommend looking at the regex to register whether a file should be considered a test file somewhere

**Comment by orenmizr** [comment]
hi, my test are running perfectly and reflected in the bottom even when they break. it is just the gutter icons that don't show up. everything else is working as expected.

**Comment by eXigentCoder** [comment]
Just installed 1.14.2 of VS Code and installed the extension and I'm getting the same issue. This was a clean install as I'm thinking of switching across from Webstorm

**Comment by bookman25** [comment]
Does anyone have a sample repo we can look at?  My guess is that it has something to do with the jest config being used.

**Comment by orenmizr** [comment]
regular setup... just pointed to jest to the files. not even sure if there is a dedicated jest file other than package json scripts

**Comment by chriskrycho** [comment]
I'm seeing this in the repo [here](https://github.com/chriskrycho/i-fp-js).

**Comment by Jipperism** [comment]
Same here, it seems to be running all tests correctly. However, I am not receiving the gutters icons (green and red circles) and InlineErrorMessages do not seem to be inserted into the file, as is shown in the gif on the front page. macOS 10.12, Node 8.1.2, Jest 21.1.0, Typescript 2.5.2.

**Comment by goncharov** [comment]
Same for me since updating to Jest 21. I think it's caused by changed output of `--showConfig` in  https://github.com/facebook/jest/pull/4078

**Comment by Jipperism** [comment]
Downgrading 20 and upgrading to 21 again somehow fixed this for me in our monorepo setup.

**Comment by orta** [comment]
There was an update last night to the extension which should help this ( #146 )

**Comment by orta** [comment]
Calling this fixed

**Comment by Jipperism** [comment]
Just stopped working for me agian. Errors are showing up in 'Problems' panel, Jest is running al tests as expected AFAICT. Inline error messages in comments and gutter icons are not showing up however. Could this have to do with yesterdays update of VS Code?

**Comment by xxxtonixxx** [comment]
I have the same problem, in one project it's working well but in another one not :confused:

**Comment by webbdylan** [comment]
I was having this issue as well. Through trial and error I was able to determine that for me the missing icons seemed to be due to me disabling the Jest extension. Once I re-eneabled the Jest extension (the one maintained by Orta Therox , Sean Poulter , Vincent Voyer & ConnectDotz ), the icons came back.

**Comment by phoenixeliot** [comment]
I have a repo that consistently reproduces this problem for just one file, but not another: https://github.com/phoenixeliot/line-puzzle/tree/6908a53aaf0964e23a2b7414922f698f0e6b42f0

The icons don't appear in Board.test.ts, but do appear in Area.test.ts. The tests in Board.test.ts do get red underlines for the lines that are related to test failures, though, so the tests are _running_.

**Comment by phoenixeliot** [comment]
<img width="1792" alt="Screen Shot 2021-12-12 at 21 58 52" src="https://user-images.githubusercontent.com/491376/145745595-27f8364e-4d65-4b2b-a678-8da7ceb97cc7.png">
<img width="1792" alt="Screen Shot 2021-12-12 at 21 59 10" src="https://user-images.githubusercontent.com/491376/145745605-ea6eb0a4-06c1-41df-8a70-7454900195af.png">

**Comment by phoenixeliot** [comment]
Is there somewhere I can get debug logs or something for this? I turned on "debug mode" in the Jest extension settings, but that didn't add any extra logs I could find.

This problem occurs regardless of any settings I have turned on or off in my VS Code settings.

**Comment by phoenixeliot** [comment]
OK, I think I've narrowed it down.

This was probably introduced when I `git mv`'d a `board.test.ts` to `Board.test.ts`. This confused VS Code, resulting in this JSON in the SQLite database for VSCode's state:

<details>
<summary>memento/workbench.parts.editor</summary>

```
{
  "editorpart.state": {
    "serializedGrid": {
      "root": {
        "type": "branch",
        "data": [
          {
            "type": "leaf",
            "data": {
              "id": 3,
              "editors": [
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/board.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/src/board.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/board.ts\",\"scheme\":\"file\"},\"preferredResourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Board.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/src/Board.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Board.ts\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"
                },
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Area.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/src/Area.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Area.ts\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"
                },
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Cell.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/src/Cell.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/src/Cell.ts\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"
                },
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/board.test.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/tests/board.test.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/board.test.ts\",\"scheme\":\"file\"},\"preferredResourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/Board.test.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/tests/Board.test.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/Board.test.ts\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"
                },
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/Area.test.ts\",\"external\":\"file:///Users/phoenix/Code/_personal_projects/line-puzzle/tests/Area.test.ts\",\"path\":\"/Users/phoenix/Code/_personal_projects/line-puzzle/tests/Area.test.ts\",\"scheme\":\"file\"},\"encoding\":\"utf8\"}"
                },
                {
                  "id": "workbench.input.settings2",
                  "value": ""
                },
                {
                  "id": "workbench.editors.files.fileEditorInput",
                  "value": "{\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"/Users/phoenix/Library/Application Support/Code/User/settings.json\",\"external\":\"vscode-userdata:/Users/phoenix/Library/Application%20Support/Code/User/settings.json\",\"path\":\"/Users/phoenix/Library/Application Support/Code/User/settings.json\",\"scheme\":\"vscode-userdata\"},\"encoding\":\"utf8\"}"
                }
              ],
              "mru": [
                3,
                6,
                5,
                4,
                0,
                1,
                2
              ]
            },
            "size": 965
          }
        ],
        "size": 609
      },
      "orientation": 1,
      "width": 965,
      "height": 609
    },
    "activeGroup": 3,
    "mostRecentActiveGroups": [
      3
    ]
  }
}
```
</details>

Note in particular that two of the editors have both a `"resourceJSON"` key and a `"preferredResourceJSON"` key, with the first one having the old lowercase filename.

When I replicate this same pattern to Area.test.ts, I get the exact same symptoms. It seems some part of the Jest extension is doing a case-sensitive filename check based on the resourceJSON filename, while other parts aren't.

**Comment by phoenixeliot** [comment]
This was involved enough that I made a new ticket: https://github.com/jest-community/vscode-jest/issues/810
