### ISSUE TITLE
Asking for v20+ when Jest 20.0.4 is installed

### ISSUE THREAD

**Issue by ManuelDeLeon** [orta/vscode-jest#132]
(hit enter by mistake)

### Environment

1. `node -v`: v7.10.0
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): -- (empty)

1. Operating system: Win10

### Steps to Reproduce

Install v2.2.0

### Expected Behavior

Not display an error

### Actual Behavior

Displays: `This extension relies on Jest 20+ features, it will continue to work, but some features may not work correctly.`

**Comment by orta** [comment]
This is likely fixed by #146 - due to the config not getting parsed
