### ISSUE TITLE
Not working with create-react-native-app (expo)

### ISSUE THREAD

**Issue by jarecsni** [orta/vscode-jest#136]
### Environment

1. `node -v`: v7.2.0
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): (empty) - but I haven't ejected.

1. Operating system: macOS Sierra, v 10.12.6

### Steps to Reproduce

Create a new app using create-react-native-app 

### Expected Behavior

Want to see the jest icon working on the status bar.

### Actual Behavior

Jest won't start, it doesn't emit any messages, etc. I can run jest on the command line, but the plugin won't work. 

I have changed this setting:
"jest.pathToJest": "[...]/node_modules/jest/bin/jest.js" - this is where I have found jest after the installation steps.

Thanks!

**Comment by orta** [comment]
I wonder if they have jest in a different position, like how create react app does - I'd recommend looking at the code for how we handle create-react-app and checking how that differs with create-react-native-app.

**Comment by anton-matosov** [comment]
I am using CRNA and had this issue too, but I found solution.
I am using per-project settings `.vscode/settings.json` and put `"jest.pathToJest": "node_modules/jest/bin/jest.js"` into it. I had to RESTART Visual Studio Code for this setting to be picked up by vscode-jest plugin (same for any other setting for vscode-jest, this is a topic for another bug tho)
After that I had to start it manually by calling `Jest: Start Runner` and it is working just fine afterwards, including coverage features (I had it enabled for the project).
I always have to start it manually after IDE restart.

**Comment by anton-matosov** [comment]
Update. Upgrading jest to 21.2.1 helped with autostart (I had 20.0.4 bundled via jest-expo@22.0.1) 
Adding yarn as explicit dependency also solves initial issue, and requires 0 changes to config.
So simple `yarn add jest --dev` solved all the issues of CRNA setup

**Comment by anton-matosov** [comment]
Fixed in #164
