### ISSUE TITLE
Option to Disable Code Coverage Overlay

### ISSUE THREAD

**Issue by jmdarling** [orta/vscode-jest#143]
### Environment

1. `node -v`: v6.10.2
2. `npm -v`: 4.6.1

1. Operating system: macOS Sierra 10.12.6

Hopefully I am not just blind and missing this, but is there a way to disable the code coverage overlay? I am working to bring an app with less than stellar coverage up to snuff, and I love this extension's features, but when 99% of your code is uncovered, the coverage overlay goes from being helpful to just being annoying.

For now I am just disabling coverage in my Jest config while using this extension but being able to toggle the feature itself would be much more elegant.

**Comment by bookman25** [comment]
There is not currently an option to toggle the coverage overlay, but I agree it does make a lot of sense.  Opened a PR with basic support for this feature.
