### ISSUE TITLE
Support suppressing the initial test run as an option

### ISSUE THREAD

**Issue by orta** [orta/vscode-jest#151]
### Steps to Reproduce

Open the jest repo with the vscode-jest enabled. It's realistically too large of a codebase to run a full run.

### Expected Behavior

We add a setting that can default to off that allows you to say this project shouldn't get the initial run.

### Actual Behavior

I run  the stop jest command 👍

**Comment by seanpoulter** [comment]
@orta, how do you feel about calling the setting `runAllTestsFirst` that default to `true`?

**Comment by orta** [comment]
Sure thing 👍
