### ISSUE TITLE
I need to run jest with a specific TZ

### ISSUE THREAD

**Issue by capaj** [orta/vscode-jest#153]
this extension has almost all the features I need. Only thing lacking is ability to run jest with a custom ENV vars.
I run my jest with TZ=UTC so that my snapshot tests match the ones on our build server. Is there any way to resolve this? Is it something I could potentially open as a PR? It would be trivial to add a single config just for passing ENV variables.

**Comment by orta** [comment]
Could you use jest's setup script to set the process env?

**Comment by Marinolinderhof** [comment]
can you set a process env in jest config? 
As a workaround i added 
```export TZ=UTC``` in my ```~/.bash_profile```

Hopefully we can do this per workspace. 

Cheers for the extension really helpful

**Comment by orta** [comment]
I mean using this setting in jest for that specific test suite to run something like

```js
process.TZ = "UTC"
```

Before every tests suite.

**Comment by capaj** [comment]
@orta not sure if it's going to work- I think at that time all the child processes are already forked so they aren't started with the time in UTC. I tried it like a year ago. Will try again.

**Comment by connectdotz** [comment]
how about jest's config [globals](https://facebook.github.io/jest/docs/en/configuration.html#globals-object)?
> A set of global variables that need to be available in all test environments.

you can use different jest.config file for different test setting, either use vscode-jest setting `jest.pathToConfig` or simply pass the config file in cli via `jest.pathToJest`, for example, `node_modules/.bin/jest --config=utc-jest.js`

it's best to adopt the jest way of doing things so you can run your test independent of vscode, especially when you consider running them later in any ci environments or automatic batch testing...

**Comment by jcollum-nike** [comment]
I was curious about this today and added 

```
  globals: {
    TZ: 'utc',
  },
``` 

to my jest.config.js. 

It didn't work. What's the solution these days?

**Comment by soorajshankar** [comment]
Try this before `describe` in your test 
`const moment = require.requireActual('moment-timezone').tz.setDefault('America/Los_Angeles');`

**Comment by jcollum** [comment]
Would that work if I don't use `moment`?

**Comment by igorbarbashin** [comment]
Prepended jest scripts with `TZ=UTC` in package.json. Works great!

```
    . . .
    "test": "TZ=UTC jest --coverage",
    "test:watch": "TZ=UTC jest --watchAll",
    . . .
```

**Comment by joetidee** [comment]
https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config

**Comment by avindra** [comment]
Pure Jest only solution (no need to modify `scripts` in package.json)

**globalSetup.js**

```
export default () => {
  process.env.TZ = 'UTC';
}
```


**package.json**

```
{

  "jest": {
      "globalSetup": "<rootDir>/globalSetup.ts",

  }

}
```

**Comment by jcollum** [comment]
Same answer as here:
https://stackoverflow.com/questions/56261381/how-do-i-set-a-timezone-in-my-jest-config

**Comment by CanKattwinkel** [comment]
@avindra I am the author of the SO, you should add to your solution that it does not work on Windows

**Comment by sfc-gh-lrejman** [comment]
Solution that worked for me: add the following option to `settings.json`:
```
"jestrunner.jestCommand": "TZ=UTC node 'node_modules/.bin/jest'"
```

**Comment by coler-j** [comment]
The core problem is: what if I want to run different tests in different timzones...

**Comment by seanpoulter** [comment]
> The core problem is: what if I want to run different tests in different timzones...

Interesting! I'd suggest you create a new issue to explore why the solution above doesn't work for you, suggest a few options for how you'd like to solve the problem(s). We can join in the conversation and help you contribute from there.

This thread from the linked comment and down might be interesting - https://github.com/vuejs/vue-test-utils/issues/193#issuecomment-528358591

Is the problem changing environment variables, or changing configurations?
