### ISSUE TITLE
does not watch file changes

### ISSUE THREAD

**Issue by jaimesangcap** [orta/vscode-jest#158]
### Environment

1. `node -v`: 8.4.0
2. `npm -v`: 5.4.0
4. `npm ls react-scripts` (if you haven’t ejected): [not CRA]

1. Operating system: OSX Sierra 10.12.5

### Steps to Reproduce

git clone https://github.com/jaimesangcap/sample-vscode-jest

yarn install

start the vscode-jest
change test assertions in `tests/staffs.test.ts`

### Expected Behavior

it should detect file changes and rerun test

### Actual Behavior

it does not watch files after initial test run

--- 

running `jest --watch` manually works and detects file changes

**Comment by orta** [comment]
This extension is calling `--watch` also, I'd recommend editing Jest's in your node modules to echo out when a file is registered by watchman to see if the same thing is happening.

**Comment by jaimesangcap** [comment]
Closing this one now since I think it's not an issue with the plugin. 
Thank you.
