### ISSUE TITLE
Fix support for create-react-app and react-scripts

### ISSUE THREAD

**Issue by seanpoulter** [orta/vscode-jest#161]
This is a new issue to aggregate existing issues for supporting `create-react-app` and `react-scripts`. The latest node LTS version doesn't install Jest where it's currently expected (in src/helpers.ts). This seems to be the cause of #39, #41, #113, and #125.

--

### Environment
1. `node -v`: 8.9.0
1. `npm -v`: 5.5.1
1. `npm ls react-scripts` (if you haven’t ejected): N/A
1. Operating system: Windows 7

1. Extension version: v2.4.1 as of 23af6f0

### Steps to Reproduce
The `create-react-app` [User Guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md) has a section for [Updating to New Releases](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases). Instead of installing newer versions of `react-scripts`, I've used this approach to bootstrap app with each supported version (>= v1.0.0) and confirm the extension doesn't work.

```
create-react-app app
cd app
npm uninstall react-scripts
npm install "react-scripts@<version>"
code --extensionDevelopmentPath=<...\vscode-jest> .
```

### Expected Behavior

The extension should detect the bootstrapped app.

### Actual Behavior

An "Unexpected token" error is thrown when Jest runs without detecting this has been bootstrapped.

![2017-11-04 -- vscode-jest -- unexpected token](https://user-images.githubusercontent.com/2585460/32402387-d455702c-c0f8-11e7-9c49-7d4e5d7ed6ea.PNG)

### Suggested Changes

- Maintain the existing check to support older versions of node/npm
- Detect `react-scripts` in `node_modules/.bin/react-scripts(.cmd)?`

**Comment by nickmccurdy** [comment]
I'm getting the `Unexpected token` error on JSX using `react-scripts` 1.1.4. Setting `jest.pathToJest` `npm test --` as a workaround fixes it, but shouldn't this be automatic?

**Comment by badsyntax** [comment]
@nickmccurdy thanks for the workaround. @orta this still seems to be an issue BTW, the test runner is using jest directly, instead of going through react-scripts.
