### ISSUE TITLE
Getting `ReferenceError: window is not defined`

### ISSUE THREAD

**Issue by bbshih** [orta/vscode-jest#165]
Any ideas on fixes or how I can continue to troubleshoot this? It works when I run my tests in the console.

### Environment

1. `node -v`: 8.6.0
2. `npm -v`: 5.5.1

1. Operating system: Mac OS Sierra 10.12.6

### Steps to Reproduce

I have jest configured in my package.json with this: 
```
"setupFiles": [
    "<rootDir>/config/jest/mockLocalStorage.js"
]
```
And in mockLocalStorage.js I defined a mockLocalStorage class and then do this: window.localStorage = new LocalStorageMock();

### Expected Behavior

Run the test normally

### Actual Behavior

 FAIL  src/containers/component.spec.js

  ● Test suite failed to run

    ReferenceError: window is not defined
      
      at Object.<anonymous> (config/jest/mockLocalStorage.js:16:1)
          at <anonymous>

**Comment by seanpoulter** [comment]
The default `testEnvironment` is `jsdom` which should provide `window`. Are you specifying anything different for the `testEnvironment` from the command line options or configuration?

**Comment by bbshih** [comment]
That fixed it. I removed it previously but didn't restart vs code. It worked after restart. Thank you!

**Comment by slonak79** [comment]
Thanks @seanpoulter this worked for me.
