### ISSUE TITLE
Not working with create react app

### ISSUE THREAD

**Issue by tomjal** [orta/vscode-jest#17]
Not sure why but it gives me "'node_modules' is not recognized as an internal or external command,
operable program or batch file." while using inside create react app APP.

**Comment by orta** [comment]
Oh interesting, I wonder if a react react app hides jest?

**Comment by orta** [comment]
Yep, the extension shouldn't even load, ok, looks like this is a feature to add

```
 ~/d/t/my-app  ls node_modules/react-scripts/node_modules/jest/bin                                                                                                                                                                                                                                   Tue 29 Nov 18:17:48 2016
jest.js
```

**Comment by orta** [comment]
Cool, I've shipped a release 1.5.0 + #20  - can you verify it works?

**Comment by tomjal** [comment]
Great, I will test it on my main project as soon as possible.

**Comment by brentatkins** [comment]
I've tried using this with create react-app and get the following error:

```
Exception raised: Process failed: spawn node_modules\.bin\jest.cmd ENOENT
```

Looks like the extension is still looking for jest inside node_modules\.bin

**Comment by orta** [comment]
This is odd, I definitely have code checking the OS and using `node_modules/react-scripts/node_modules/.bin/jest.cmd` - any chance you can run it in the debugger and see what's up with this function - https://github.com/orta/vscode-jest/blob/master/src/helpers.ts#L15-L20

**Comment by brentatkins** [comment]
Created PR #38

**Comment by TroySchmidt** [comment]
This isn't work for me either.  I have a create-react-app and the react-scripts 0.9.2.  I don't have either of the folders in the activationEvents, but jest testing is running fine.  The extension won't autoStart right now and when I start manually even with a path to jest of npm test -- I still get Process failed: spawn npm ENOENT.
