### ISSUE TITLE
Not ignoring files specified in jest config under package.json

### ISSUE THREAD

**Issue by jaimesangcap** [orta/vscode-jest#170]
### Environment

1. `node -v`: v8.4.0
2. `npm -v`: 5.5.1
4. `npm ls react-scripts` (if you haven’t ejected): NOT CRA

1. Operating system: OSX Sierra

### Steps to Reproduce
Given this directory structure
```
__tests__/
--- helpers/
------ server.ts <--- no test describe/it method here
--- routes/
------expense.test.ts <--- one passing test
```
and jest config under package.json
```
"jest": {
    "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testPathIgnorePatterns":[
      "<rootDir>/__tests__/helpers" <----- ignore helper folder
    ],
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json"
    ]
  }
```
### Expected Behavior
When running the `jest` command on cli, it skips the `helpers` folder and shows one test passes (without failing test). Therefore vscode-jest should also display all test passes in the status bar

### Actual Behavior
Reports there is a failing test shown in the status bar. when clicked shows the ouput panel with error 

```
PASS __tests__/routes/expenses.test.ts


FAIL __tests__/helpers/server.ts

  ● Test suite failed to run

    Your test suite must contain at least one test.
      
      at node_modules/jest-cli/build/test_scheduler.js:95:22
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at <anonymous>


Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.599s, estimated 2s
Ran all test suites related to changed files.
```

**Comment by seanpoulter** [comment]
Any luck troubleshooting this @jaimesangcap? Is this in a repo we can clone to try and reproduce the problem?

**Comment by seanpoulter** [comment]
I can't reproduce your issue @jaimesangcap. Have a look using [this example repo](https://github.com/seanpoulter/vscode-jest--issue-170).

**Comment by jaimesangcap** [comment]
@seanpoulter thank you for providing example repo, I will check it and get back.

**Comment by jaimesangcap** [comment]
I've just tested it with the example repo and my actual project and it works well now. That's strange. Thank you for looking and spent time on it.

**Comment by Skriptach** [comment]
@seanpoulter I faced same issue. But now your example repo is not available
