### ISSUE TITLE
template literals in describe / it calls cause dot indicator issue

### ISSUE THREAD

**Issue by dan-weaver** [orta/vscode-jest#171]
### Environment

1. `node -v`: 8.9.1
2. `npm -v`: 5.5.1
4. `npm ls react-scripts` (if you haven’t ejected): none

1. Operating system: Windows 10 AND OSX Sierra

### Steps to Reproduce
I reproduced this by using this example https://github.com/facebook/jest/tree/master/examples/react.  Clone the repo then edit one of the tests to use a template literal instead of a string. e.g.

```
describe("test", function() {
  it("should not work", function() {
     expect(true).toBe(false)
   })
})
```
would become

```
describe(`test`, function() {
  it(`should not work`, function() {
     expect(true).toBe(false)
   })
})
```
### Expected Behavior
the dot indicator (passed/failed/not run) should stay up to date with the state of the test.  

### Actual Behavior
However, no matter what, it always shows up in the "not run" state.

![2017-11-16_1249](https://user-images.githubusercontent.com/1619461/32909634-ab553eb8-cacc-11e7-8b0a-f25854eb0123.png)

![2017-11-16_1249_001](https://user-images.githubusercontent.com/1619461/32909641-af56886e-cacc-11e7-899b-9d74601a2739.png)
--- 

Note we are looking for someone to take responsibility around keeping create-react-app up to date and working, could this be you?

**Comment by orta** [comment]
Yeah, it'd make sense that the lookup for the test would fail with template strings (we do find the tests via the AST) - you're welcome to take a look at this in jest-editor-extensions.

**Comment by dan-weaver** [comment]
thought that was probably the case.. Thanks I'm going to close this then and take a look over at jest-editor-extensions

**Comment by seanpoulter** [comment]
@dan-weaver, I'm happy to submit a PR for that package. Looks like most of the work is adding more tests. ;)
