### ISSUE TITLE
Handle on-boarding in a nicer way

### ISSUE THREAD

**Issue by gabro** [orta/vscode-jest#18]
Ref: https://twitter.com/gabro27/status/803592079188365316

When installing the extension and opening an existing test file, all dots are white.
This is because jest only runs on changed files.

This is not a big deal, but the experience is not the most rewarding, as in "I installed this extensions to see green dots! Where are my green dots?!"

Possible ways of handling this:

- add a "run all" command that can be manually triggered
- make white dots empty green dots
- nothing, this is just me being nit-picky

Others?

**Comment by orta** [comment]
Yeah, I think the unknown should be a green circle 👍

**Comment by orta** [comment]
This is in
