### ISSUE TITLE
Green Indicator Dot Missing?

### ISSUE THREAD

**Issue by cgatian** [orta/vscode-jest#187]
### Environment

1. `node -v`: 8.7.0
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): n/a

1. Operating system: Windows 10

### Steps to Reproduce

Edit failing test

### Expected Behavior

After failing test runs, a green dot/indicator should display for success

### Actual Behavior

No dot is displayed to indicate sucess

![jest](https://user-images.githubusercontent.com/1752170/33769721-39988f1c-dbf9-11e7-90ae-12ceed1bf979.gif)

**Comment by seanpoulter** [comment]
Looks like we made a logical error then swept it under the rug. :disappointed:  Hopefully we can roll this one out quick.

Sounds like the right time to suggest more tests for the win! :medal_sports:
