### ISSUE TITLE
Missing space in failure result

### ISSUE THREAD

**Issue by elgervb** [orta/vscode-jest#22]
Just a minor issue, but there is a space missing in the failure result. 
Now: `: trueReceived: false`

Should be `: true Received: false`

![image](https://cloud.githubusercontent.com/assets/356204/20742279/6b5bcc94-b6cf-11e6-9dd2-d631c5b63c0f.png)

Anyway, thanks for a nice plugin ;-)

**Comment by orta** [comment]
Weird, I specifically had code for this: https://github.com/orta/vscode-jest/blob/master/src/lib/test_reconciler.ts#L113

**Comment by elgervb** [comment]
Just updated to the latest version. Now I don't see the Jest plugin any more..
When I run the `Start Jest Runner` command, then I get the error message: _command 'io.orta.jest.start' not found_

Something looks wrong...

**Comment by orta** [comment]
With 1.6.1?

**Comment by elgervb** [comment]
Works like a charm now ;-)

**Comment by web2style** [comment]
I have this issue with the latest version of the plugin (1.6.4): http://take.ms/Qi5FC

**Comment by orta** [comment]
Aye, me too, I think we can get some more tests in jest-test-support to make better single-lined errors once https://github.com/facebook/jest/pull/2192 is merged

**Comment by orta** [comment]
Yeah, this look fixed now 👍
