### ISSUE TITLE
Support for .ts files

### ISSUE THREAD

**Issue by con-ssc** [orta/vscode-jest#27]
I'm writing my code and my tests in TypeScript. Could you add support for that too?

**Comment by orta** [comment]
I don't think we do anything to _not_ support it, want to clone and run the project and see what's up?

**Comment by orta** [comment]
Hrm, I guess the babylon parser may not be able to parse a typescript test file - might need something else that can generate an AST of a typescript file? Though I'd expect your test files to look identical to a ES6 JS file, so it may "just work".

**Comment by con-ssc** [comment]
I think some of the suggestions might work but for example, the test indicator is not shown.

**Comment by bookman25** [comment]
I'm definitely getting parser errors on the typescript files.  We use a preprocessor in jest for runtime, however babylon appears to be parsing the source file and not the processed output that jest is using.

**Comment by bookman25** [comment]
So I think I'm going to try to work on this, assuming nobody else is.

**Comment by orta** [comment]
👍

**Comment by gyzerok** [comment]
👍  for the feature as well

**Comment by orta** [comment]
Yeah, that AST example should get you there - I've been using the unit tests to quickly iterate on the parser incase you have started ( also, depending on when you start you might want to consider adding it to facebook/jest ( re: https://github.com/facebook/jest/pull/2192 ))

**Comment by bookman25** [comment]
I saw the jest stuff, had a feeling my code was going to have to move.  I was able to get TS parser working and loading ItBlocks last night.  Still have a ways to go before it's ready for a PR.  I'm thinking I'll need to port this code into jest, maybe as a separate package so that it doesn't get loaded when it's not necessary.  (Since a lot of projects won't need to parse ts files)

**Comment by orta** [comment]
@bookman25 one way to work around having that issue is to pipe to `tsc` to get the AST JSON - then we're not deploying typescript with the jest-extension-support, but can work with the version that inevitably you'd have to have inside your node_modules folder

**Comment by bookman25** [comment]
@orta I think this can be closed, just needs a new release with the latest version of the plugin.

**Comment by bookman25** [comment]
Fixed with 2.0
