### ISSUE TITLE
Support running jest command from a path that is not the project's root

### ISSUE THREAD

**Issue by orta** [orta/vscode-jest#28]
This https://github.com/orta/vscode-jest/pull/25 wasn't quite right in the end, I need to run `npm run jest -- --watch` from the root of the jest repo in order to ensure the build transformations work right. So ideally, I'd be able to say "if I open at this folder, use this as cwd for jest".

**Comment by luisrudge** [comment]
is this the reason I'm getting `Exception raised: Process failed: spawn node_modules\.bin\jest.cmd ENOENT`?

**Comment by orta** [comment]
Nah, I don't think so, do those files exist for you?  what is the path to your Jest script

**Comment by luisrudge** [comment]
`"test": "jest --coverage",`

![image](https://cloud.githubusercontent.com/assets/941075/20809109/1fd09a5c-b7ec-11e6-8f46-78a555f25897.png)

**Comment by orta** [comment]
can you try setting your `jest.pathToJest` for this project to be `npm test --`?

**Comment by luisrudge** [comment]
where do I set this up?

**Comment by orta** [comment]
in your project settings `.vscode/settings.json`

**Comment by luisrudge** [comment]
`Exception raised: Process failed: spawn npm ENOENT`

**Comment by orta** [comment]
@luisrudge would recommend cloning this extension and having a look at what's going on

**Comment by orta** [comment]
Closing, this isn't really the fix I was looking for.
