### ISSUE TITLE
it.only is not found and registered as a test case

### ISSUE THREAD

**Issue by orta** [orta/vscode-jest#29]
before
![screen shot 2016-12-01 at 08 54 15](https://cloud.githubusercontent.com/assets/49038/20787454/c1a159aa-b7a3-11e6-9dc8-1b08dc3fcbaa.png)
after
![screen shot 2016-12-01 at 08 54 19](https://cloud.githubusercontent.com/assets/49038/20787456/c2d3b052-b7a3-11e6-8139-b9de22790540.png)

**Comment by bookman25** [comment]
Fixed by: https://github.com/facebook/jest/pull/2327 It'll need vscode-jest to pull these changes (once jest creates a new release or linking to commit and shipping).

Closing as completed, feel free to re-open.
