### ISSUE TITLE
Test status decoration not updated until pane is selected.

### ISSUE THREAD

**Issue by alloy** [orta/vscode-jest#34]
![vscode-jest-status-not-updating](https://cloud.githubusercontent.com/assets/2320/20861127/16997402-b956-11e6-8782-a6226937c63f.gif)

**Comment by orta** [comment]
ah yeah! The is definitely not happening. You know, I never considered this workflow

I think it makes a lot of sent though.

**Comment by orta** [comment]
Yep - this is in 👍
