### ISSUE TITLE
Cannot install npm packages with this plugin installed

### ISSUE THREAD

**Issue by robcaldecott** [orta/vscode-jest#37]
I'm on Windows using npm3.

When I have this plugin installed and a project open that uses Jest, I cannot npm install any plugins unless I close VS Code. I am greeted with errors that look like files in use, probably because this plugin has something locked. A way to easily turn the watcher off would be useful here: even better would for it to stop when npm install is running.

**Comment by orta** [comment]
You can turn the watcher off with the command `Stop Jest Runner`

Hrm, I'm not sure if it's possible for the extension to know when an install is happening, any ideas?

**Comment by bookman25** [comment]
This is actually an issue I ran into with jest.  When the jest watcher is running it locks lots of files and as a result npm install fails.

**Comment by bookman25** [comment]
Closing.  I think the only action here is to `Stop Jest Runner` when updating packages and it's not something that the plugin can do itself.
