### ISSUE TITLE
Installed, have script "test" setup...but...not seeing anything?

### ISSUE THREAD

**Issue by PeteDuncanson** [orta/vscode-jest#44]
Hey Orta,

Trying to give this a whirl. Got it installed via the extension menu, enabled it. In my package.json I have this script:

"scripts": {
    "stats": "webpack -p --profile --json > stats.json",
    "production": "webpack -progress -p",
    "test": "jest"
  },

But in VSCode I'm not seeing the lovely output you have in the footer, what am I missing?

Cheers

Pete

**Comment by orta** [comment]
Do you have the status bar at the bottom at all?

**Comment by PeteDuncanson** [comment]
Nope, don't even have the little "Jest" text in the bottom right. Ideas?

**Comment by orta** [comment]
cool - can you see if anything in here applies to your project please: https://github.com/orta/vscode-jest#troubleshooting

**Comment by PeteDuncanson** [comment]
Found the issue! I was opening VSCode on a child folder not the root folder of the project so it was not finding the package.json file. Its a huge .net project and the React side of it is only in one folder so for ease I was opening just that. Would be nice if it looked up the folders to see if it could find a package.json further up?

**Comment by orta** [comment]
Hrm a quick look through the [activation events](https://code.visualstudio.com/docs/extensionAPI/activation-events) shows nothing that would be of use for us here. I think the best option might be to update the README to say that you can start it in any project by running the "Start Jest Runner" command (this is how I do my work inside Jest itself)

**Comment by orta** [comment]
Alright - I've given an overview around the in the README - thanks for your patience @PeteDuncanson
