### ISSUE TITLE
Show failing and passed test in ts code

### ISSUE THREAD

**Issue by afaayerhan** [orta/vscode-jest#51]
don't know if this is already implemented yet. showing passed and failed test inline in a typescript file ( like in the gif shown but for js) because this is only shown for js files currently. if there is a way to make it show the same either via sourcemaps or something else can someone show me? appreciate you help in advance thanks

**Comment by orta** [comment]
2.0.x works for TypeScript, so I think you'll need to run through the troubleshooting section of the README in order to diagnose your issue 👍 


![screen shot 2016-12-21 at 9 43 01 am](https://cloud.githubusercontent.com/assets/49038/21393312/e00969dc-c761-11e6-9df3-00da33b1c7ac.png)

**Comment by afaayerhan** [comment]
@orta everything is working fine can close this now
