### ISSUE TITLE
Doesn't display JS error message, 

### ISSUE THREAD

**Issue by nfour** [orta/vscode-jest#58]
First; this is a very cool extension.

When you get a JS error you'd expect it to display as thus:

```js
state = STORE.getStateXXX() // TypeError: STORE.getStateXXX is not a function
```

Instead it's 

```js
state = STORE.getStateXXX() //
```
Still useful, but could use a message.

**Comment by orta** [comment]
Agreed, wanna try take a stab at it? 

This [is where we extract](https://github.com/facebook/jest/blob/master/packages/jest-editor-support/src/TestReconciler.js#L91-L97) the message from the JSON output from Jest ( if you run with `--json` ) I think we could try pick out specific bits of info for specific fails

**Comment by nfour** [comment]
Sounds reasonable, I'll have time on the weekend to take a poke I hope.

**Comment by orta** [comment]
Related - https://github.com/facebook/jest/issues/2444

**Comment by capaj** [comment]
for me, it doesn't display any messages at all. Running on vscode 1.8.1 and jest 18.1.0

Any pointers @orta ?

**Comment by orta** [comment]
I think realistically you'll need to run the extension in dev mode and see what's happening with the failed diagnostics: https://github.com/orta/vscode-jest/blob/master/src/JestExt.ts#L234
