### ISSUE TITLE
showing error on the wrong test in Typescript 

### ISSUE THREAD

**Issue by afaayerhan** [orta/vscode-jest#62]
![image](https://cloud.githubusercontent.com/assets/8157594/21543557/3faf5cf6-cdd0-11e6-97d8-f314741c137a.png)

**Comment by orta** [comment]
Wonder if we're not handling multiline `expect`s correctly, can you test by making the expect above a single line and seeing if that fixes it?

**Comment by bookman25** [comment]
Can you create a simple reproduce repo?  I was thinking maybe it has something to do with async/await but I was unable to reproduce.

**Comment by afaayerhan** [comment]
@orta @bookman25 believe the issue is gone just like that I have no idea it gave me lot of problems I also have problem reproducing it. the stuff is a ghost. would close this issue and reopen if it again PISS OUT
