### ISSUE TITLE
No tests found related to files changed since last commit.

### ISSUE THREAD

**Issue by UncleFirefox** [orta/vscode-jest#65]
Hi!

I've installed the plugin, made sure I got this in package.json:

`"test": "jest --watchAll --config node_modules/ca-ui-module-test/__jestDist__/jest.config"`

But the runner keeps telling me all the time:

```
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.
```

I can do ``yarn test`` and everything works normally. Am I missing something? What should I look for? Is there anything I can activate that gives more more info?

Thanks!

**Comment by orta** [comment]
Just to confirm, you understand how the watch mode works ( in that it only looks at tests related [to the current git diff](https://egghead.io/lessons/javascript-use-jest-s-interactive-watch-mode))?

So that I know whether this is a configuration problem or not

**Comment by jakefolio** [comment]
I just recently upgraded vscode to 1.8.1, and I am getting a similar response when I save my test files.

Here is my launch.json

```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/jest-cli/bin/jest.js",
            "stopOnEntry": false,
            "args": ["--runInBand"],
            "cwd": "${workspaceRoot}",
            "runtimeArgs": [
                "--debug-brk",
                "-i",
                "--colors"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/dist/"]
        }
    ]
}
```

Here are my scripts from `package.json`:

```javascript
"scripts": {
    "build": "npm run clean && webpack -p --config ./webpack.config.prod.js",
    "clean": "rm -rf ./dist",
    "start": "webpack-dev-server --config ./webpack.config.dev.js",
    "start:prod": "npm run build && NODE_ENV=production node ./src/server",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage",
    "test:coverage:ci": "jest --coverage --runInBand"
  }
```

**Comment by alex-ketch** [comment]
I'm also experiencing this with VS Code Version 1.13.1.
You can test with a new app created with https://github.com/wmonk/create-react-app-typescript.

The first screenshot shows that the file is seen by Git as dirty, but the VSCode-Jest does not register the changes.

Running the command straight from terminal (second screenshot) run the appropriate test.

Thanks for the wonderful plugin, and let me know if I can help in further debugging this issue.

![screen shot 2017-07-08 at 22 31 01](https://user-images.githubusercontent.com/1646307/27990716-5946dc9a-642d-11e7-8d37-4b0cd62298ee.png)


<img width="927" alt="screen shot 2017-07-08 at 22 28 36" src="https://user-images.githubusercontent.com/1646307/27990714-4eea63ac-642d-11e7-8e08-c961b9fe0fee.png">

**Comment by orta** [comment]
^ This is like an issue at the Jest level, this extension is only running `jest --watch` with some extra CLI args at this pint

**Comment by alex-ketch** [comment]
@orta It was my mistake. I had to change `pathToJest` inside the workspace settings.
I initially didn't realize that I could set it to a command.

```
"jest.pathToJest": "npm test --"
```

If you'd like, I can make a PR making a note of this in the README.
Thanks again for your time!

**Comment by orta** [comment]
Sure, yeah - better docs is always a great improvement!

**Comment by seanpoulter** [comment]
Closing this stale issue. The [Troubleshooting](https://github.com/orta/vscode-jest#troubleshooting) section of the README mentions `pathToJest`.

**Comment by Sphinxs** [comment]
`npm test a`
