### ISSUE TITLE
Option to override the arguments passed when debuggin

### ISSUE THREAD

**Issue by michaeljota** [orta/vscode-jest#675]
### Environment

1. `node -v`: 14.4.0
1. `npm -v`: 6.14.8
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@26.6.3
1. your vscode-jest settings if customized:
    - jest.pathToJest? `ng test`
    - jest.pathToConfig? [fill]
    - anything else that you think might be relevant? 
      - I'm using Angular CLI, with `@angular-builders/jest` builder to allow Jest to run with `ng test`. Because of how Schematics are, you can't declare additional undocumented arguments. 

1. Operating system: Windows

### Prerequisite
- are you able to run Jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) `ng test`

### Steps to Reproduce

Try to override the arguments passed to Jest when calling the `debug` option above a test.

### Expected Behavior

An option could allow me to override the arguments passed.

### Actual Behavior

Even when you can enhance with other stuff, additional arguments will always be passed. Those are the arguments I would like to handle.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment]
you should be able to customize the debug config and pass additional arguments: https://github.com/jest-community/vscode-jest#debug-config

**Comment by michaeljota** [comment]
I'm using this right now, but still, there are additional arguments that are being passed to the test every time. 

This is my configuration in my launch.json file.
```json
...
    {
      "type": "node",
      "request": "launch",
      "name": "vscode-jest-tests",
      "program": "${workspaceFolder}/node_modules/@angular/cli/bin/ng",
      "args": ["test", "{appName}", "--run-in-band"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
...
```
This is the output when I try to run "debug"
```
...
'C:\Program Files\nodejs\node.exe' '.\node_modules\@angular\cli\bin\ng' 'test' '{appName}' '--run-in-band' 'app.component.spec.ts' '--testNamePattern' 'should create the app' 
Support for camel case arguments has been deprecated and will be removed in a future major version.
Use '--test-name-pattern' instead of '--testNamePattern'.
Unknown option: 'app.component.spec.ts'
Waiting for the debugger to disconnect...
```

As you can see, the file name and the --testNamePattern are being added as arguments, and I can't update that.

**Comment by connectdotz** [comment]
@michaeljota if you used the debug codeLens, the additional parameters you mentioned above will be automatically appended so you can debug the corresponding test. If you don't want the extension to append these parameters, you can simply copy or rename the test config and run them directly via vscode's debugging: https://code.visualstudio.com/docs/editor/debugging

**Comment by michaeljota** [comment]
Yes, that's what I would like to be able to override. The parameters that the CodeLens command sends to the terminal. I understand those are probably to pick just the right test, but it would be nice if I could override those and be able to run debug test from the CodeLens.

**Comment by connectdotz** [comment]
@michaeljota what is the desired override?

**Comment by michaeljota** [comment]
I would like to omit the file name, so I don't have an error when I tried to debug.

**Comment by connectdotz** [comment]
I see, so you want to use the `--test-name-pattern` (or `--testNamePattern`) without the file name itself because angular can not handle the fileName parameter... is that correct?

Please keep in mind that without the fileName, if you have the same test name in multiple files, they will all be executed. This led me to believe that omit the file name is incorrect or at least taking a step backward since our goal is to execute this explicit test in this explicit file... 

I am not familiar with angular so not sure why angular does not support such use-case. IMHO, It might benefit more people for angular to support the proper use of jest cmd than us adding potential incorrect customization...

**Comment by michaeljota** [comment]
Angular support for Jest is through a 3rd party plugin, and currently, the problem is that Angular strictly checks the arguments that a plugin can handle and because Jest doesn't actually have an option to pass files, because, anything that is not an option is considered a file.

I'm aware this can cause another issue, but it could be workarounded in another way.

**Comment by connectdotz** [comment]
hmmm... I am thinking maybe we could use [--testPathPattern](https://jestjs.io/docs/cli#--testpathpatternregex) instead of appending the file directly... would that work for your use case?

**Comment by aberasarte** [comment]
I'm experiencing this same issue and I think that adding `--testPathPattern` instead of appending the file would be a nice fix.

**Comment by michaeljota** [comment]
@connectdotz Yes, I think that might work. If you need someone to test this, I'm available.

**Comment by connectdotz** [comment]
@michaeljota  great, thanks. Angular has a few issues with this extension right now, we are working to resolve them, will ping you when they are available.

**Comment by szechyjs** [comment]
any updates here?

**Comment by top-master** [comment]
## Update 2026:
To prevent the error:
```
Option "testPathPattern" was replaced by "--testPathPatterns"
```

We need in the `.vscode/launch.json` file, the following:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "name": "vscode-jest-tests.v2",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
      "args": [
        "--runInBand",
        "--watchAll=false",
        "--test-name-pattern",
        "${jest.testNamePattern}",
        "--test-path-patterns",
        "${jest.testFilePattern}"
      ],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "sourceMaps": true,
      "smartStep": true
    }
  ]
}
```

And for Windows, in the `.vscode/settings.json` file we need:
```json
{
  "jest.jestCommandLine": "\"./node_modules/.bin/jest.cmd\"",
  "jest.rootPath": ".",
  "jest.shell": "cmd.exe",
}
```

**Note** that the `launch.json` file is only needed for debugging the tests with VSCode, and the `settings.json` file is only needed for running and watch-mode of the tests.
