### ISSUE TITLE
Allow option for arguments (harmony flag)

### ISSUE THREAD

**Issue by tslater** [orta/vscode-jest#69]
I run just like this:
```
node  --harmony-async-await ./node_modules/.bin/jest
```
I would like to suggest adding a setting for command line variables.

**Comment by orta** [comment]
I think this is possible with the jest command setting already

**Comment by orta** [comment]
yeah, you can change `jest.pathToJest` to be `node  --harmony-async-await ./node_modules/.bin/jest` and it should work 👍

**Comment by tslater** [comment]
Thanks! Sorry for my oversight. I looked through the settings and didn't
see any docs. I thought that the path was just a path, not a command.
ᐧ
