### ISSUE TITLE
TypeError: cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by tinovyatkin** [orta/vscode-jest#75]
<img width="534" alt="screen shot 2017-02-06 at 12 44 09 pm" src="https://cloud.githubusercontent.com/assets/5350898/22656602/42233f80-ec6a-11e6-9c50-ac9d037048c7.png">

VSCode 1.9 Stable (trace logs shows .vscode-insiders because my extensions folder is shared between them and symlinked)

**Comment by goddva** [comment]
Got the same error, and the error is coming from [jest-editor-support](https://github.com/facebook/jest/tree/master/packages/jest-editor-support), when it tries to parse the .babelrc file...

Try to add an empty plugins array to your .babelrc file... example
```
{
  "presets": ["es2015"]
}
```
to
```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": []
}
```

**Comment by tinovyatkin** [comment]
@goddva I have no `babelrc` at this project, it's pure node 7.5, no transpilling, but `--harmony` - may it be a problem?

**Comment by tinovyatkin** [comment]
@goddva found rests of `babelrc`, removed it, and it solves the problem! Thank you!

**Comment by goddva** [comment]
This will be solved in next version of [jest-editor-support](https://github.com/facebook/jest/tree/master/packages/jest-editor-support), as the bugfix has been [merged](https://github.com/facebook/jest/issues/2819)

**Comment by orta** [comment]
<3
