### ISSUE TITLE
The test runner fails to start when using powershell with the new 'shell' setting because arguments are passed with '--'

### ISSUE THREAD

**Issue by vviotto** [orta/vscode-jest#786]
### Environment

1. `vscode-jest version`: 4.2.1
2. `node -v`: 14.15.0
3. `npm -v`: 6.14.8
4. `npm ls jest`: 27.1.1
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? Default
    - jest.autoRun? Default
    - anything else that you think might be relevant?
    ```json
    {
      "jest.shell": "powershell"
    }
    ```
6. Operating system: Windows

### Prerequisite
- are you able to run jest test from the command line? Yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce
Just try to use the new option to change the default shell to 'powershell', the test runner will fail

### Relevant Debug Info

The error displayed in the output window in vscode:
```
At line:1 char:48
+ ... repo_root_path\node_modules\.bin\jest.cmd" --testLocationInResults --json  ...
+                                                  ~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'testLocationInResults' in expression or statement.
At line:1 char:1
+ "repo_root_path\node_modules\.bin\jest.cmd" --testLocationInResults  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The '--' operator works only on variables or on properties.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
Jest process "watch-tests" ended unexpectedly
 see troubleshooting: https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting
```

### Expected Behavior

Test runner started without issues

### Actual Behavior

The test runner fails to start

**Comment by connectdotz** [comment]
I don't think we can generate specific commands for each possible shell people might use. If users customized the shell, it is possible that they will need to use jestCommandLine and/or other settings to adapt the system accordingly. 

Feel free to ask questions if anybody got stuck with similar issues...
