### ISSUE TITLE
Add a "show Jest channel" command

### ISSUE THREAD

**Issue by orta** [orta/vscode-jest#88]
From the keyboard you can't get to the Jest output info. Need a mouse, that's a shame. 👍

**Comment by bookman25** [comment]
Quick View command has something that works out of the box: https://code.visualstudio.com/updates/v1_8#_view-picker

**Comment by orta** [comment]
Ah, that is new to me! This does work ( though it's maybe a big janky on the Mac ) I still think it's worth the noise for It (as it would show in the command palette )

**Comment by bookman25** [comment]
I think it's a good idea also, was just pointing out an option until it gets implemented 👍

**Comment by orta** [comment]
lols, decided to look at it, went to the folder and there was already a diff for it in staging. Must have done it after drinking at some point on my honeymoon.
