### ISSUE TITLE
Issues with Babylon Parser (in jest-editor-support)

### ISSUE THREAD

**Issue by anarresk** [orta/vscode-jest#92]
I couldn't get on with `wallabyjs`, and was pleasantly surprised to find this! However, it turns out that for some reason there were a bunch of issues in the `BabylonParser` within `jest-editor-support` - I'm not entirely certain what caused them (as no one else seems to be having these issues) - must be something specific to my `.babelrc`. However, a few adjustments to the source made it work _pretty much_ alright - there's still some issues which I'm investigating, but wanted to share here for anyone else struggling to get this plugin working (yay for the pretty coloured circles!).

It's mainly to do with poor (or non-existent) defensive coding. I had a lot of "cannot read type of undefined" and "cannot read type of null" - adding in checks for these in the `searchNodes` function of the `jest-editor-support/build/parsers/BabylonParser.js` stopped these.

ie:
```
// before
.filter(declaration => isFunctionDeclaration(declaration.init.type))
.forEach(declaration => searchNodes(declaration.init.body, file));
// after
.filter(declaration => isFunctionDeclaration(declaration.init ? declaration.init.type : null))
.forEach(declaration => searchNodes(declaration.init ? declaration.init.body : null, file));

// before
element.type === 'ExpressionStatement' &&
element.expression.type === 'AssignmentExpression' &&
// after
element.type === 'ExpressionStatement' &&
element.expression &&
element.expression.type === 'AssignmentExpression' &&
element.expression.right &&
```

**Comment by orta** [comment]
I threw together some PRs this morning that should also help the babelRC issues, but I need a jest deployment to ship https://github.com/orta/vscode-jest/pull/90 https://github.com/facebook/jest/pull/3212

I'd definitely love any stability improvements for babel to get into jest-editor-support, as I'm primarily using TypeScript and don't have any projects using babel + Jest

**Comment by anarresk** [comment]
Sure, I'll just defensively code that BabelParser :) Will reference here when I have a PR

**Comment by orta** [comment]
<3

**Comment by TuiKiken** [comment]
I have the same issues =(

**Comment by orta** [comment]
I think this is deployed now with 2.2.0
