### ISSUE TITLE
Do interactive keystrokes work?

### ISSUE THREAD

**Issue by mosesoak** [orta/vscode-jest#96]
Hi, how do I interact with the test runner using these inputs?

```
Watch Usage
 › Press a to run all tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```

**Comment by orta** [comment]
They don't - vscode doesn't support that. Maybe once #93 is done it could.

**Comment by mosesoak** [comment]
Actually I figured out a way, by starting watch in the in-editor terminal (`./node_modules/jest/bin/jest.js --watch`) - works great and shows syntax highlighting as well.

Not sure if vscode can spawn multiple terminal panes but that might be a cool way to solve for this.

If I'm running watch manually like that, not sure I need this plugin at all(?)
