### ISSUE TITLE
disable inline errors that are shown ass comments 

### ISSUE THREAD

**Issue by afaayerhan** [orta/vscode-jest#97]
![image](https://cloud.githubusercontent.com/assets/8157594/24832145/b878c0fc-1cb1-11e7-9735-f42c2c44e526.png)
how to disable this. or implement an option to disable showing inline errors as interfare and cause confusion editing the test file.

**Comment by orta** [comment]
I'd happily take an option for it, could also dismiss them if the lines.length for the file changes

**Comment by dandv** [comment]
These errors are confusing if you're debugging a test and VSCode also runs Jest on that same test in the background (#352), because the error may appear *after* you've stepped over that line. Yes, that might mean the test isn't a pure function, but while developing it, that's ok.
